### ISSUE TITLE
Forcing SSL

### ISSUE THREAD

**Issue by cancan101** [juanifioren/django-oidc-provider#10]
The README states:

> Despite that implementation MUST support TLS. You can make request without using SSL. There is no control on that.

If you want to suggest to the users, something like this:
https://github.com/rdegges/django-sslify can be used to prevent non SSL connections.

**Comment by juanifioren** [comment]
Thinking about this, the idea is that when you are running with `DEBUG = True` no control is needed, otherwise, the package SHOULD prevent non SSL connections.

**Comment by wojtek-fliposports** [comment]
Since Django version 1.8 You have [SecurityMiddleware](https://docs.djangoproject.com/en/1.9/ref/middleware/#django.middleware.security.SecurityMiddleware) and simply just add in the test/production settings:

`SECURE_SSL_REDIRECT = True
SECURE_SSL_HOST = 'your_domain.com'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_SECONDS = 3600*24
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'`

**Comment by wojtek-fliposports** [comment]
Maybe we can adapt this:
```
#decorators.py
from django.http import HttpResponseBadRequest
from django.conf import settings

def secure_required(view_func):
    def _wrapped_view_func(request, *args, **kwargs):
        if not settings.DEBUG and request and not request.is_secure():
            raise HttpResponseBadRequest()
        return view_func(request, *args, **kwargs)
   return _wrapped_view_func
```

and then in:
```
# views.py
from django.utils.decorators import method_decorator
from oidc_provider.lib.decorators import secure_required

@method_decorator(secure_required, name='dispatch')
class AuthorizeView(View):
```

**Comment by juanifioren** [comment]
For now, we'll keep this optional
