### ISSUE TITLE
Why are scope query params used at the token endpoint?

### ISSUE THREAD

**Issue by runner4444** [juanifioren/django-oidc-provider#186]
When grant_type is authorization_code and refresh_token the scope was declared in the auth request, and is already associated with the token, hence `token.code` should be used to create the id token, not `self.params['scope']`. See https://github.com/juanifioren/django-oidc-provider/blob/v0.5.x/oidc_provider/lib/endpoints/token.py#L203

**Comment by wojtek-fliposports** [comment]
I will mark this question as `spec_required` but from my perspective it's a bug because you could change scope on every token refresh on even code exchange.

**Comment by runner4444** [comment]
In the spec, I don't see the mention of scope being passed in the token request (http://openid.net/specs/openid-connect-core-1_0.html#TokenEndpoint). I think it definitely is a bug as you thought, because otherwise an application could extend the tokens scope without consent from the user.

**Comment by wojtek-fliposports** [comment]
I agree, changed label to BUG. Can You provide PR for this?

**Comment by runner4444** [comment]
I will try to get to it by the end of this week. Will be a really minor change. I plan to leave the "create_access_token_response_dic" method the same.

**Comment by suutari-ai** [comment]
This was actually causing a problem for me, since the OIDC client lib I was using, didn't send the scope when requesting a token (as it's not supposed to) and therefore the returned ID token didn't have the right scope.

This is what I did to make it work:

https://github.com/suutari-ai/django-oidc-provider/commit/729624356a59ebfad24f7bd8adc6e6dcaa5f4fa1

That was preferring the scope from request parameters and if there is none, then use the scope of the code object. Now that I read the discussion here it seems that correct fix would be to ignore any scope parameter and rather just use the scope from the code object, i.e. simply change that line to `scope=token.scope`. Do you agree that it would be a correct fix?

**Comment by wojtek-fliposports** [comment]
I can agree. Scope should be taken from first auth request, when checking consents.
Can You provide some PR with tests for this ? If not, I will fix this asap and ask @juanifioren to release this security fix

**Comment by suutari-ai** [comment]
Looking into this currently. The fix is easy, but I'd like to double check the docs about this and write some tests too as suggested.

Btw. found out that not only the "code" grant type but also the other two grant types, "refresh token" and "password", have a similar problem.

**Comment by wojtek-fliposports** [comment]
I think `password` is tricky.. look at this https://tools.ietf.org/html/rfc6749#section-4.3 
This `password` is a OAuth2 Username-Password Authentication Flow. So for parameter `scope`I need to dive in into spec

**Comment by suutari-ai** [comment]
Yep, for the password grant type it seems to be correct to use the scope provided to the token endpoint. Only problem with that in the current implementation is that the scope parameter is not splitted correctly when passed to create_id_token, i.e. `"openid email"` is being passed but correct would be `["openid", "email"]`.
