### ISSUE TITLE
When do you think this library would be production use ready?

### ISSUE THREAD

**Issue by rsung** [juanifioren/django-oidc-provider#26]
I'm interested in using this library but I can't find any roadmap indicating when it should be production ready.  Please advise.

Regards
-r

**Comment by juanifioren** [comment]
Hi @rsung ,

Thanks for your interest, we are using this package on a production site with no problem (with more than 100k users registered), have clients using PHP, Drupal and NodeJS with their respective RP implementations.
I think you ask this because there is a message on docs that advice about not using on a production environment (or doing it by your own risks).
This is because, we are still working on important security things about the spec (besides that some OIDC clients doesn't implement them).
The most important at the moment is: [ID Tokens MUST be signed/encrypted with RS256 at least](https://github.com/juanifioren/django-oidc-provider/issues/15).
Running over SSL is another one.

Besides this, we handle most of the [security considerations](http://openid.net/specs/openid-connect-core-1_0.html#Security).

Do not hesitate to ask me if you have any further questions.

Greetings.

_-Ignacio_

**Comment by rsung** [comment]
Thank you for the prompt response.  We'll move forward with this tool.
