### ISSUE TITLE
Logout with redirect on Django 4.1+

### ISSUE THREAD

**Issue by fzzylogic** [juanifioren/django-oidc-provider#416]
Noticed this, just mentioning fwiw. From 4.1, [Django requires POST to logout](https://forum.djangoproject.com/t/showing-method-not-allowed-get-users-logout/26044). 

[EndSessionView](https://github.com/juanifioren/django-oidc-provider/blob/977c80f4ae87dfc19a3cc300f3436c6d01bf1078/oidc_provider/views.py#L346C15-L346C15) inherits from [LogoutView](https://github.com/django/django/blob/dc26a3d563b1e1d98d40f5d351a6a61c34f12d98/django/contrib/auth/views.py#L124), so redirect to end_session_endpoint is blocked in Django 4.1+. 

Redirect is [correct](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout) as per the OID spec. Maybe have an intermediate function that posts to EndSession?

**Comment by juanifioren** [comment]
Hi @fzzylogic, `EndSessionView` was rewritten into a custom view instead of Django `LogoutView`. This improvement will be released on the next version (likely in a few days).
Now the end session endpoint will support POSTing and other features like consent prompt.

More info: https://django-oidc-provider.readthedocs.io/en/develop/sections/sessionmanagement.html#rp-initiated-logout
