### ISSUE TITLE
Ignoring OIDC_SKIP_CONSENT_ENABLE in POST request

### ISSUE THREAD

**Issue by wojtek-fliposports** [juanifioren/django-oidc-provider#90]
I have question to handling POST request in https://github.com/juanifioren/django-oidc-provider/blob/v0.3.x/oidc_provider/views.py#L104 ?
```Python
 89:    def post(self, request, *args, **kwargs):
 90:
 91:        authorize = AuthorizeEndpoint(request)
 92:
 93:        allow = True if request.POST.get('allow') else False
 94:
 95:        try:
 96:            authorize.validate_params()
 97:             
 98:            if not allow:
 99:                raise AuthorizeError(authorize.params.redirect_uri,
100:                                     'access_denied',
101:                                     authorize.grant_type)
102:
103:            # Save the user consent given to the client.
104:            authorize.set_client_user_consent()
```
And some additional questions:
Why You validating params before checking "allow" in POST ?. Is where any spec saying that "allow" must be in POST request ?

**Comment by juanifioren** [comment]
### OIDC_SKIP_CONSENT_ENABLE in POST request

Well there is no need to check for OIDC_SKIP_CONSENT_ENABLE in POST request because the GET request to the Authorization Endpoint happens first, so it will actually SKIP the consent and return the code directly (without hitting the POST way). I think saving on the database everytime the user gives consent to an APP is OK. 

What do you think about it?.

### Why validating params before checking "allow" in POST?

Can be after, actually it could be better.

### Why "allow" must be in POST request?

Actually the allow param in the Auth request is just an implementation of:

https://tools.ietf.org/html/rfc6749#section-4.1.1
```
   If the request is valid,
   the authorization server authenticates the resource owner and obtains
   an authorization decision (by asking the resource owner or by
   establishing approval via other means).
```
http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

```
When interacting with the End-User, the Authorization Server MUST
employ appropriate measures against Cross-Site Request Forgery
```

That's why I use django Cross-Site Request Forgery protection with forms.

Do you think there is a better way to handle this?
